### PR TITLE
Fix commons-io and snakeyaml vulnerabilities

### PR DESCRIPTION
**Pull request by sunilnagavelli**
Please refer to the issue `Requesting updated jar with commons-io and snakeyaml latest versions
` https://github.com/signalfx/signalfx-java-tracing/issues/146 for more details

### CODE REVIEW

**Comment by breedx-splk** [comment]
Hi @sunilnagavelli, thanks for submitting this dependency update. I see that the build is failing due to a glassfish related problem:

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.glassfish.jersey:jersey-bom:3.1.0-M5.
```

I noticed that you also included a major version upgrade for `testCompile` in your changeset. Can you omit that and see if the build gets better? Thanks!

**Comment by sunilnagavelli** [comment]
> Hi @sunilnagavelli, thanks for submitting this dependency update. I see that the build is failing due to a glassfish related problem:
> 
> ```
> Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.glassfish.jersey:jersey-bom:3.1.0-M5.
> ```
> 
> I noticed that you also included a major version upgrade for `testCompile` in your changeset. Can you omit that and see if the build gets better? Thanks!

Thank you for the response @breedx-splk , i am trying this now, i was trying to tweak this with the latest glass fish version, but as you mentioned, i think i will omit this.

**Comment by sunilnagavelli** [comment]
> > Hi @sunilnagavelli, thanks for submitting this dependency update. I see that the build is failing due to a glassfish related problem:
> > ```
> > Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.glassfish.jersey:jersey-bom:3.1.0-M5.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I noticed that you also included a major version upgrade for `testCompile` in your changeset. Can you omit that and see if the build gets better? Thanks!
> 
> Thank you for the response @breedx-splk , i am trying this now, i was trying to tweak this with the latest glass fish version, but as you mentioned, i think i will omit this.

@breedx-splk, i have tried to omit this in the file dd-java-agent/instrumentation/glassfish/glassfish.gradle

```
dependencies {
  testCompile project(':dd-java-agent:instrumentation:servlet:request-3')
  testCompile project(':dd-java-agent:instrumentation:grizzly-2')

  // testCompile group: 'org.glassfish.main.extras', name: 'glassfish-embedded-all', version: '5.0'
  latestDepTestCompile group: 'org.glassfish.main.extras', name: 'glassfish-embedded-all', version: '+'
}
```
But I ran into this error:

```
> Task :dd-java-agent:instrumentation:glassfish:compileTestGroovy
Note: /home/circleci/signalfx-java-tracing/dd-java-agent/instrumentation/glassfish/src/test/groovy/TestServlets.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
startup failed:
/home/circleci/signalfx-java-tracing/dd-java-agent/instrumentation/glassfish/src/test/groovy/GlassFishServerTest.groovy: 13: unable to resolve class org.glassfish.embeddable.GlassFishRuntime
 @ line 13, column 1.
   import org.glassfish.embeddable.GlassFishRuntime
   ^
```
Might be we need to disable this in a different way, could you please shed some light on this.

**Comment by breedx-splk** [comment]
@sunilnagavelli Thanks for trying. It didn't seem to help, but I did look at confirm that the circleci build has been failing with glassfish related issues for more than 2 years. 🤦🏻  

Let me look at a few more things, but I think this should be fine to get merged. Let's leave the glassfish line out completely please.

**Comment by sunilnagavelli** [comment]
> @sunilnagavelli Thanks for trying. It didn't seem to help, but I did look at confirm that the circleci build has been failing with glassfish related issues for more than 2 years. 🤦🏻
> 
> Let me look at a few more things, but I think this should be fine to get merged. Let's leave the glassfish line out completely please.

oh ok @breedx-splk , i get it now :), sure, please do check!

**Comment by breedx-splk** [comment]
@sunilnagavelli Hey it looks like [snakeyaml 1.30 also has some CVEs](https://mvnrepository.com/artifact/org.yaml/snakeyaml/1.30). Can you please bump that to 1.32?

**Comment by sunilnagavelli** [comment]
> @sunilnagavelli Hey it looks like [snakeyaml 1.30 also has some CVEs](https://mvnrepository.com/artifact/org.yaml/snakeyaml/1.30). Can you please bump that to 1.32?

My bad, I missed that, thank you for pointing that out to me @breedx-splk.

Also, i was trying to find a way to omit the glassfish entirely(not sure if it is suggested) in order to get the build run successfully, but could not find a way to do that, just wanted to inform you.

**Comment by breedx-splk** [comment]
> Also, i was trying to find a way to omit the glassfish entirely(not sure if it is suggested) in order to get the build run successfully, but could not find a way to do that, just wanted to inform you.

Oh sorry, I meant omit the _change_ not the dependency. I should have been clearer.

**Comment by sunilnagavelli** [comment]
> > Also, i was trying to find a way to omit the glassfish entirely(not sure if it is suggested) in order to get the build run successfully, but could not find a way to do that, just wanted to inform you.
> 
> Oh sorry, I meant omit the _change_ not the dependency. I should have been clearer.

Oh ok!, could you please point out to me to make those changes, here is the latest error for the testCompile omission(will revert this though), would like to see how to omit the change.

ERROR:
```
> Task :dd-java-agent:instrumentation:glassfish:compileTestGroovy
Note: /home/circleci/signalfx-java-tracing/dd-java-agent/instrumentation/glassfish/src/test/groovy/TestServlets.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
startup failed:
/home/circleci/signalfx-java-tracing/dd-java-agent/instrumentation/glassfish/src/test/groovy/GlassFishServerTest.groovy: 13: unable to resolve class org.glassfish.embeddable.GlassFishRuntime
 @ line 13, column 1.
   import org.glassfish.embeddable.GlassFishRuntime
   ^
```

**Comment by breedx-splk** [comment]
> if possible, will you be able to do add commit from your side @breedx-splk ? just asking.

Just change the line in `dd-java-agent/instrumentation/glassfish/glassfish.gradle` from
```
// testCompile group: 'org.glassfish.main.extras', name: 'glassfish-embedded-all', version: '5.0'
```

back to the original
```
testCompile group: 'org.glassfish.main.extras', name: 'glassfish-embedded-all', version: '4.0'
```

You'll still get that groovy test compilation failure tho. But if you revert that change we can merge this PR and I can cut a release for you with the updated dependencies.

**Comment by sunilnagavelli** [comment]
> > if possible, will you be able to do add commit from your side @breedx-splk ? just asking.
> 
> Just change the line in `dd-java-agent/instrumentation/glassfish/glassfish.gradle` from
> 
> ```
> // testCompile group: 'org.glassfish.main.extras', name: 'glassfish-embedded-all', version: '5.0'
> ```
> 
> back to the original
> 
> ```
> testCompile group: 'org.glassfish.main.extras', name: 'glassfish-embedded-all', version: '4.0'
> ```
> 
> You'll still get that groovy test compilation failure tho. But if you revert that change we can merge this PR and I can cut a release for you with the updated dependencies.

Great!, I got that, just reverted the change :)

**Review by breedx-splk — APPROVED** [review]
Thanks. Let's get these deps updated.

**Comment by sunilnagavelli** [comment]
> Thanks. Let's get these deps updated.

Sure, Thank you @breedx-splk , and once that is done we will be able to see the updated jar, v0.48.0-sfx**9**?

**Pull request merged**
